export interface Faculty {
  faculty_ID: number,
  college_ID: number,
  first_name: string,
  teaching_position: string,
  middle_name: string,
  ext_name: string,
  last_name: string,
  isAdmin: number,
  birthdate: string,
  age: number,
  citizenship: string,
  civil_status: string,
  sex: string,
  email: string,
  password: string,
  employment_status: number,
  phone_number: string,
  region: string,
  province: string,
  language: string,
  city: string,
  barangay: string,
  profile_image: string,
  cover_image: string,
  college: string
}
