export interface Profile {
    faculty_ID: number,
    college_ID: number,
    college_name: string,
    college_abbrev:string,
    teaching_position: string,
    isAdmin: boolean,
    first_name: string,
    last_name: string,
    birthdate: Date,
    age: number,
    citizenship: string,
    civil_status: string,
    sex: string,
    email: string,
    employment_status: boolean,
    phone_number: string,
    middle_name: string,
    ext_name: string,
    region: string,
    province: string,
    language: string,
    city: string,
    barangay: string,
    profile_image: string,
    cover_image: string
}